### ISSUE TITLE
Such talented work done, can I ask you for a hint?

### ISSUE THREAD

**Issue by JooHyukKim** [pearcetm/svs-deidentifier#12]
Hi my name is Vince Kim, a univ student from South Korea.

For weeks, I have been trying to delete the number of n pages from the fullest resolution from svs file, because our slides are too large to store.

And finally, I run into your work and trying to figure out how to and having hard time.
I was wondering if you would like to give some hint?
It will mean sooooooooo much to me.

Below is what I'd like to do.

thank you in advance! 
cheers.

def downsize(svsfile, n_pages):
    # read svsfile
    # there are 9 pages from the tiled pyramid images
    # 0th image being the full resolution image ( largest )
    # if n_pages equals 2,
    # remove first two largest images
    # save as svs file

**Comment by pearcetm** [comment]
Hi @JooHyukKim , so sorry I didn't see this! I did not have notifications turned on for the repository unfortunately. I hope you were able to make something work eventually.

**Comment by JooHyukKim** [comment]
> Hi @JooHyukKim , so sorry I didn't see this! I did not have notifications turned on for the repository unfortunately. I hope you were able to make something work eventually.

Yes,  I found a work around. 
I will close this issue as a result. 
Keep up the great work! Cheers
